export const styles = {
  postTitleInputContainer: {
    width: '100%',
    flex: 0.1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: '#C4C4C4',
    paddingHorizontal: 5,
  },
  postTitleInput: {
    fontSize: 12,
    fontWeight: '500',
    paddingHorizontal: 5,
    height: 30,
    width: '70%',
  },
  postTitleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#28235F',
    marginLeft: 30,
  },
  postContextContainer: {
    width: '100%',
    flex: 0.3,
    paddingLeft: 35,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderBottomColor: '#C4C4C4',
    borderBottomWidth: 1,
    paddingHorizontal: 5,
  },
  postContextInput: {
    fontSize: 12,
    fontWeight: '500',
    paddingHorizontal: 5,
    height: 30,
    width: '80%',
  },
  postPhotoContainer: {
    padding: 15,
    flex: 0.6,
  },
  addPhotoContainer: {
    paddingLeft: 18,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 30,
  },
  addPhotoText: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#28235F',
  },
  addedPhotoContainer: {
    paddingLeft: 18,
    height: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  addedPhoto: {
    width: 80,
    height: 50,
    borderRadius: 10,
    marginRight: 15,
  },
}
